#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from chiral4form.localization import modmax_symbolic_report

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--pure-stress',type=Path,default=Path('verification/degree12/global_reachability_manifest.json'));ap.add_argument('--inventory',type=Path,default=Path('verification/degree12/generalized_candidate_inventory.json'));ap.add_argument('--discovery',type=Path,default=Path('verification/degree12/generalized_discovery.json'));ap.add_argument('--completion',type=Path,default=Path('verification/degree12/generalized_completion_manifest.json'));ap.add_argument('--json-output',type=Path,default=Path('verification/degree12/conformal_scope_report.json'));ap.add_argument('--md-output',type=Path,default=Path('docs/CONFORMAL_SCOPE_REPORT.md'));a=ap.parse_args()
    pure=json.loads(a.pure_stress.read_text());inv=json.loads(a.inventory.read_text());disc=json.loads(a.discovery.read_text());comp=json.loads(a.completion.read_text());mod=modmax_symbolic_report()
    deg={r['id']:int(r['degree']) for r in inv['candidates']};sel=disc['selected_extras'];counts={str(d):sum(deg[x]==d for x in sel) for d in (4,6,8,10,12)};omitted=sorted(set(deg)-set(sel),key=lambda x:(deg[x],x))
    out={'schema':1,'status':'physical_and_conformal_scope_report','pure_stress_orbit_dimensions':{'degree8':4,'degree10':6,'degree12':10},'pure_stress_global_degree12':True,'generalized_completion_selected_count':len(sel),'generalized_selected_counts_by_degree':counts,'primitive_candidates_omitted_by_selected_set':omitted,'modmax_prior_work_reproduction':mod,
         'scope_conclusion':'The pure-stress and generalized-completion theorems concern finite polynomial interactions analytic at the zero-field point through degree 12. The ModMax-like potential b*sqrt(I4) is nonanalytic at I4=0 and is outside that theorem class.',
         'paper_safe_interpretation':'The finite polynomial classification gives a constructive D=10 example in which stress invariants occupy a proper subset of interaction space while genuine additional F5-dependent scalar structures complete the polynomial sector; it does not settle nonanalytic ModMax reachability.'}
    a.json_output.parent.mkdir(parents=True,exist_ok=True);a.json_output.write_text(json.dumps(out,indent=2)+'\n')
    md=f"""# Conformal / physical scope report\n\n## Certified finite-polynomial results\n\n- Pure-stress global orbit dimensions: **4 -> 6 -> 10** through degrees 8, 10, 12.\n- Genuine generalized completion through degree 12: **certified**.\n- Selected primitive extras in the strong global-translation construction: **{len(sel)}**.\n- Selected counts by degree: `{counts}`.\n- Primitive candidates omitted by the selected construction: `{omitted}`.\n\n## ModMax-like sector\n\nThe repository reproduces the published algebraic ModMax-like identity on the patch `I4 != 0`: conformal homogeneity = `{mod['conformal_homogeneity_verified']}`, stress-square identity = `{mod['stress_square_identity_verified']}`.\n\nHowever, `V = b sqrt(I4)` is nonanalytic at `I4 = 0`. The finite polynomial theorems proved in this repository are analytic-at-zero truncations through field degree 12. Therefore the paper must **not** state that the degree-12 theorem proves or disproves nonanalytic ModMax reachability.\n\n## Paper-safe physical interpretation\n\nThe computation gives a finite-degree constructive realization of the D=10 phenomenon that stress invariants alone occupy a proper subset of the available interaction space, while genuine additional F5-dependent scalar structures can complete the polynomial sector.\n"""
    a.md_output.parent.mkdir(parents=True,exist_ok=True);a.md_output.write_text(md)
    print('PASS: STEP 4 SCOPE REPORT');print('selected extras:',len(sel));print('counts by degree:',counts);print('omitted primitives:',omitted);print('ModMax inside polynomial theorem:',False);print('WROTE:',a.json_output);print('WROTE:',a.md_output)
if __name__=='__main__':main()
